// <auto-generated />
namespace DataAcessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddWriterTitle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddWriterTitle));
        
        string IMigrationMetadata.Id
        {
            get { return "202204031927325_Add-WriterTitle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
